name: autofix.ci
on:
  pull_request:
    paths:
      - "**/*.pkr.hcl"
      - ".aqua/aqua.yaml"
permissions:
  contents: read
jobs:
  autofix:
    runs-on: ubuntu-26.04
    timeout-minutes: 15
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Check changed files
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: changes
        with:
          filters: |
            packer:
              - "**/*.pkr.hcl"
            aqua:
              - ".aqua/aqua.yaml"

      - name: Install aqua
        uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.63.0
          aqua_args: i -l

      - name: Format Packer files
        if: steps.changes.outputs.packer == 'true'
        run: packer fmt .

      - name: Fix aqua-checksums.json
        if: steps.changes.outputs.aqua == 'true'
        run: aqua upc -prune

      - name: Run autofix.ci
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
