name: renovate-config-validator

on:
  pull_request:
    paths:
      - "renovate.json"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-26.04
    timeout-minutes: 5
    container:
      image: renovate/renovate:44.149.2@sha256:4a93eba384999995555d48ff194d5013230fe44142260292cdaf9e7bd45ed949
      options: --user root
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Validate Renovate Configuration
        run: renovate-config-validator --strict renovate.json
