name: renovate-config-validator

on:
  pull_request:
    paths:
      - "renovate.json"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-26.04
    timeout-minutes: 5
    container:
      image: renovate/renovate:44.148.3@sha256:69e3c20b19f901ca7b02f609216d5ccf0fa700387001f099817852da3dfb617c
      options: --user root
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Validate Renovate Configuration
        run: renovate-config-validator --strict renovate.json
