name: renovate-config-validator

on:
  pull_request:
    paths:
      - "renovate.json"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Validate Renovate Configuration with renovate-config-validator
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v2.1.0
